version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: autoclick-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    environment:
      MONGO_INITDB_DATABASE: autoclick_db
    networks:
      - autoclick-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: autoclick-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=autoclick_db
      - ENVIRONMENT=production
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - autoclick-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: autoclick-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - autoclick-network

  # Nginx reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: autoclick-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - autoclick-network

volumes:
  mongodb_data:
  mongodb_config:

networks:
  autoclick-network:
    driver: bridge